---
- name: Example playbook with additional fields
  hosts: "{{ target_host }}"
  tasks:
    - name: Ensure Apache is installed
      package:
        name: apache2
        state: present

    - name: Display message
      debug:
        msg: "Hello, {{ user_name }}! Welcome to {{ target_host }}."
